package com.vedx.vedxsuper.strategy.engine

import android.util.Log
import com.vedx.vedxsuper.model.market.TickData
import com.vedx.vedxsuper.model.market.Candle
import com.vedx.vedxsuper.strategy.candle.CandleBuilder
import com.vedx.vedxsuper.strategy.indicator.MultiSuperTrendEngine
import com.vedx.vedxsuper.strategy.indicator.MultiSuperTrendResult
import com.vedx.vedxsuper.strategy.options.ExpiryManager
import com.vedx.vedxsuper.strategy.options.SellingStrikeSelector
import com.vedx.vedxsuper.strategy.signal.BandDetector
import com.vedx.vedxsuper.strategy.signal.BandInfo
import com.vedx.vedxsuper.utils.StrategyUtils.safe
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.util.concurrent.ConcurrentHashMap
import kotlin.math.abs

/**
 * Signal generated by the institutional strategy engine.
 */
data class InstitutionalSignal(
    val type: String,
    val action: MasterAction,
    val confidence: Int,
    val reason: String,
    val optionSymbol: String,
    val price: Double,
    val target: Double,
    val target2: Double = 0.0,
    val finalTarget: Double = 0.0,
    val stopLoss: Double,
    val quantity: Int = 0,
    val riskReward: Double = 0.0,
    val timestamp: Long,
    val optionBand: Int = 0,
    val structure: MarketStructure = MarketStructure.NO_STRUCTURE,
    val zoneMatchScore: Int = 0,
    val indexZone: ZoneStatus? = null,
    val optionZone: ZoneStatus? = null,
    val marketStrength: Int = 0,
    val premiumExpansion: Double = 0.0,
    val delta: Double = 0.0,
    val gamma: Double = 0.0,
    val vega: Double = 0.0,
    val theta: Double = 0.0,
    val ivChange: Double = 0.0,
    val oiChange: Long = 0
)

/**
 * Core engine for institutional trading strategy coordination.
 */
class InstitutionalStrategyEngine(
    val indexSymbol: String,
    private val riskManagementEngine: RiskManagementEngine = RiskManagementEngine(),
    private val timeframe: Int = 15,
    private val lotSizeProvider: (String) -> Int = { symbol ->
        when {
            symbol.contains("BANKNIFTY") -> 30
            symbol.contains("SENSEX") -> 20
            symbol.contains("FINNIFTY") -> 60
            symbol.contains("NIFTY") -> 65
            else -> 65
        }
    }
) {
    private var strategyConfig = com.vedx.vedxsuper.model.trade.StrategyConfig()

    fun updateConfig(config: com.vedx.vedxsuper.model.trade.StrategyConfig) {
        this.strategyConfig = config
    }

    private companion object {
        const val MAX_SIGNAL_HISTORY = 50
        const val SIGNAL_SPAM_WINDOW_MS = 500
        val BAND_IDS = intArrayOf(2, 3, 4, 5, 6, 7, 8)

        const val TYPE_CALL = "BUY_CALL"
        const val TYPE_PUT = "BUY_PUT"
        const val TYPE_EXIT = "EXIT"
        const val TYPE_TRAIL = "TRAIL"
        const val TYPE_PARTIAL = "PARTIAL_EXIT"
        const val TYPE_SCALP = "SCALP"
        const val TYPE_WATCH = "WATCHING"
        const val TYPE_PREPARE = "PREPARING"
        const val TYPE_SELL_CALL = "SELL_CALL"
        const val TYPE_SELL_PUT = "SELL_PUT"

        const val TAG = "InstEngine"
        const val EPSILON = 0.000001
    }

    private val defaultLotSize = lotSizeProvider(indexSymbol)
    private val indexAgents = BAND_IDS.map { NeuralBandAgent(multiplier = it, isIndex = true) }
    private val indexCandleBuilder = CandleBuilder(timeframe)
    private val indexStEngine = MultiSuperTrendEngine()
    private val bandDetector = BandDetector()

    private val processingScope = CoroutineScope(Dispatchers.Default + SupervisorJob())
    private val engineMutex = Mutex()

    private val indexTickChannel = Channel<TickData>(Channel.CONFLATED)
    private val optionTickChannel = Channel<Pair<TickData, Double>>(Channel.CONFLATED)

    /**
     * Internal state for a specific option strike.
     */
    data class OptionState(
        val candleBuilder: CandleBuilder,
        val agents: List<NeuralBandAgent>,
        val stEngine: MultiSuperTrendEngine = MultiSuperTrendEngine(),
        val stateEngine: TrendStateEngine = TrendStateEngine(),
        var strength: StrengthMetrics = StrengthMetrics(),
        var lastLtp: Double = 0.0,
        var previousLtp: Double = 0.0,
        var peakPrice: Double = 0.0,
        var entryPrice: Double = 0.0,
        var premiumExpansion: Double = 0.0,
        var lastOi: Long = 0,
        var oiChange: Long = 0,
        var lastIv: Double = 0.0,
        var ivChange: Double = 0.0,
        var volume: Long = 0,
        var lastBid: Double = 0.0,
        var lastAsk: Double = 0.0,
        var lastUpdateTime: Long = System.currentTimeMillis(),
        var lastHeavyCalcTime: Long = 0L,
        var lastClosedTimestamp: Long = 0L,
        var lastStResult: MultiSuperTrendResult? = null
    )

    private val centralBrain = NeuralCentralBrain()
    private val strengthEngine = MarketStrengthEngine()
    private val trendStateEngine = TrendStateEngine()
    private val regimeEngine = MarketRegimeEngine()
    private val structureEngine = MarketStructureEngine()
    private val optionIntelligenceEngine = OptionChainIntelligenceEngine()
    private val masterDecisionEngine = MasterDecisionEngine()
    private val zoneEngine = SuperTrendZoneEngine()
    private val zoneMatchEngine = ZoneMatchEngine()
    private val correlationEngine = CorrelationEngine()
    private val liquidityEngine = LiquidityEngine()
    private val fakeReversalEngine = FakeReversalEngine()
    private val trendMemoryEngine = TrendMemoryEngine()
    private val learningEngine = AdaptiveLearningEngine()
    private val sellingSelector = SellingStrikeSelector(indexSymbol, lotSizeProvider)
    private val expiryManager = ExpiryManager()

    private val _signals = MutableStateFlow<List<InstitutionalSignal>>(emptyList())
    val signals = _signals.asStateFlow()

    private val _indexMultiTrend = MutableStateFlow<MultiSuperTrendResult?>(null)
    val indexMultiTrend = _indexMultiTrend.asStateFlow()

    private val _indexZoneStatus = MutableStateFlow<ZoneStatus?>(null)
    val indexZoneStatus = _indexZoneStatus.asStateFlow()

    private var lastCachedIndexReports: List<AgentReport> = emptyList()
    private var lastCachedIndexPrice: Double = 0.0
    private val lastSignalTimestamps = ConcurrentHashMap<String, Long>()

    private var indexStrength: StrengthMetrics = StrengthMetrics()
    private var currentRegime: MarketRegime = MarketRegime.SIDEWAYS
    private var currentStructure: MarketStructure = MarketStructure.NO_STRUCTURE
    private var lastIndexStResult: MultiSuperTrendResult? = null

    private val optionStates = ConcurrentHashMap<String, OptionState>()
    private var lastCleanupTime = 0L

    init {
        processingScope.launch {
            for (tick in indexTickChannel) {
                processIndexTickLocked(tick)
            }
        }
        processingScope.launch {
            for (data in optionTickChannel) {
                processOptionTickLocked(data.first, data.second)
            }
        }
    }

    /**
     * Initializes the engine with historical candles.
     */
    fun initialize(candles: List<Candle>) {
        if (candles.isEmpty()) return
        indexCandleBuilder.initialize(candles)
        val aggregated = indexCandleBuilder.candles.value
        if (aggregated.isNotEmpty()) {
            val st = indexStEngine.calculate(aggregated)
            if (st != null) {
                lastIndexStResult = st
                _indexMultiTrend.value = st
            }
        }
    }

    /**
     * Processes live index ticks via channel (backpressure handling).
     */
    fun onIndexTick(tick: TickData, vix: Double = 15.0) {
        if (tick.symbol != indexSymbol) return
        indexTickChannel.trySend(tick)
    }

    private suspend fun processIndexTickLocked(tick: TickData, vix: Double = 15.0) {
        if (tick.timestamp - lastCleanupTime > 3600000) {
            cleanupOldOptions(tick.timestamp)
        }

        if (riskManagementEngine.preTradeCheck(currentRegime, currentStructure) != null) return

        indexCandleBuilder.onTick(tick)
        val indexCandles = indexCandleBuilder.candles.value
        if (indexCandles.isEmpty()) return

        engineMutex.withLock {
            indexStrength = strengthEngine.calculateStrength(tick, indexCandles)
            val stResult = indexStEngine.calculate(indexCandles) ?: return@withLock
            lastIndexStResult = stResult
            _indexMultiTrend.value = stResult

            val atr = abs(stResult.st2.upperBand - stResult.st2.lowerBand) / 4.0
            currentRegime = regimeEngine.identifyRegime(indexCandles, stResult, indexStrength, atr)

            val maxExpansion = optionStates.values.asSequence().maxOfOrNull { it.premiumExpansion } ?: 0.0
            currentStructure = structureEngine.updateStructure(indexCandles, stResult, indexStrength, currentRegime, maxExpansion)
            _indexZoneStatus.value = zoneEngine.identifyZone(tick.ltp, stResult, indexCandles, isIndex = true, vix = vix)

            lastCachedIndexReports = coroutineScope {
                indexAgents.map { agent ->
                    async { agent.process(candles = indexCandles, currentPrice = tick.ltp, timestamp = tick.timestamp, vix = vix) }
                }.awaitAll()
            }
            lastCachedIndexPrice = tick.ltp

            val bandInfo = bandDetector.detect(tick.ltp, stResult, isIndex = true, vix = vix)
            trendStateEngine.updateState(tick, stResult, stResult, bandInfo, bandInfo, indexStrength, currentRegime, indexCandles.last().isComplete)
        }
    }

    /**
     * Processes live option ticks via channel.
     */
    fun onOptionTick(tick: TickData, indexPrice: Double, vix: Double = 15.0) {
        if (regimeEngine.isTradingPaused(currentRegime)) return
        optionTickChannel.trySend(tick to indexPrice)
    }

    private suspend fun processOptionTickLocked(tick: TickData, indexPrice: Double, vix: Double = 15.0) {
        val indexSt = lastIndexStResult ?: return
        val state = optionStates.getOrPut(tick.symbol) {
            OptionState(candleBuilder = CandleBuilder(timeframe), agents = BAND_IDS.map { NeuralBandAgent(it, false) })
        }

        synchronized(state) {
            updateOptionState(state, tick)
        }

        if (tick.timestamp - state.lastHeavyCalcTime < 250) return

        engineMutex.withLock {
            state.lastHeavyCalcTime = tick.timestamp
            val optionCandles = state.candleBuilder.candles.value
            if (optionCandles.isEmpty()) return@withLock

            val indicators = calculateOptionIndicators(state, tick, optionCandles, indexPrice, vix, indexSt) ?: return@withLock
            val intelligence = runIntelligenceStudy(tick, state, optionCandles, indicators.first, indexSt, indexPrice, vix)

            evaluateOptionSignals(state, tick, indicators, indexSt, intelligence)
            evaluateOptionSelling(tick, indexSt, vix)
        }
    }

    private fun evaluateOptionSelling(
        tick: TickData,
        indexSt: MultiSuperTrendResult,
        vix: Double
    ) {
        if (riskManagementEngine.getState().activeExposure > 0) return

        val daysToExpiry = expiryManager.getDaysToExpiry(indexSymbol)
        val strikePrice = extractStrikePrice(tick.symbol)
        val isCall = tick.symbol.contains("CE")

        val candidate = if (isCall) {
            sellingSelector.selectOtmCall(lastCachedIndexPrice, indexSt, vix, daysToExpiry, currentStructure, indexStrength)
        } else {
            sellingSelector.selectOtmPut(lastCachedIndexPrice, indexSt, vix, daysToExpiry, currentStructure, indexStrength)
        }

        if (candidate != null && abs(candidate.strikePrice - strikePrice) < 1.0) {
            if (candidate.confidence >= 70) {
                val action = if (isCall) MasterAction.SELL_CALL else MasterAction.SELL_PUT
                val signal = InstitutionalSignal(
                    type = if (isCall) TYPE_SELL_CALL else TYPE_SELL_PUT,
                    action = action,
                    confidence = candidate.confidence,
                    reason = candidate.reason,
                    optionSymbol = tick.symbol,
                    price = tick.ltp,
                    target = candidate.premiumTarget,
                    stopLoss = candidate.stopLossPremium,
                    quantity = lotSizeProvider(indexSymbol),
                    timestamp = tick.timestamp,
                    structure = currentStructure,
                    marketStrength = indexStrength.trendStrength.toInt()
                )
                emitSignal(signal)
            }
        }
    }

    private fun extractStrikePrice(symbol: String): Double {
        return try {
            val matches = Regex("\\d+").findAll(symbol).toList()
            matches.lastOrNull()?.value?.toDouble() ?: 0.0
        } catch (e: Exception) { 0.0 }
    }

    private fun isMarketCompressed(indexSt: MultiSuperTrendResult): Boolean {
        val bands = listOf(indexSt.st2, indexSt.st3, indexSt.st4, indexSt.st5, indexSt.st6, indexSt.st7, indexSt.st8)
        val spread = bands.maxOf { it.upperBand } - bands.minOf { it.lowerBand }
        return spread < (indexSt.master.value * 0.08)
    }

    private fun updateOptionState(state: OptionState, tick: TickData) {
        state.lastUpdateTime = tick.timestamp
        state.oiChange = tick.openInterest - state.lastOi
        state.lastOi = tick.openInterest
        state.ivChange = (tick.iv - state.lastIv).safe()
        state.lastIv = tick.iv
        state.volume = tick.volume
        state.lastBid = tick.bid
        state.lastAsk = tick.ask
        state.candleBuilder.onTick(tick)

        // Track previous LTP for accurate change detection
        state.previousLtp = state.lastLtp
        state.lastLtp = tick.ltp

        // Track peak price for Trailing Stop Loss
        if (tick.ltp > state.peakPrice) state.peakPrice = tick.ltp
    }

    private suspend fun calculateOptionIndicators(
        state: OptionState,
        tick: TickData,
        candles: List<Candle>,
        indexPrice: Double,
        vix: Double,
        indexSt: MultiSuperTrendResult
    ): Triple<MultiSuperTrendResult, BandInfo, BandInfo>? {
        state.strength = strengthEngine.calculateStrength(tick, candles)
        val optionSt = state.stEngine.calculate(candles) ?: return null
        state.lastStResult = optionSt

        val indexBand = bandDetector.detect(indexPrice, indexSt, true, vix)
        val optionBand = bandDetector.detect(candles.last().close, optionSt, false, vix)

        return Triple(optionSt, optionBand, indexBand)
    }

    private suspend fun runIntelligenceStudy(
        tick: TickData,
        state: OptionState,
        candles: List<Candle>,
        optionSt: MultiSuperTrendResult,
        indexSt: MultiSuperTrendResult,
        indexPrice: Double,
        vix: Double
    ): IntelligenceReport = coroutineScope {
        val ltp = state.lastLtp
        val optionReportsDeferred = state.agents.map { async { it.process(candles = candles, currentPrice = ltp, timestamp = state.lastUpdateTime, vix = vix) } }
        val indexReports = if (abs(indexPrice - lastCachedIndexPrice) < 1.0 && lastCachedIndexReports.isNotEmpty()) {
            lastCachedIndexReports
        } else {
            indexAgents.map { async { it.process(candles = indexCandleBuilder.candles.value, currentPrice = indexPrice, timestamp = indexCandleBuilder.candles.value.lastOrNull()?.timestamp ?: 0L, vix = vix) } }.awaitAll()
        }
        val optionReports = optionReportsDeferred.awaitAll()
        val decision = centralBrain.coordinate(
            indexReports = indexReports,
            optionReports = optionReports,
            optionSymbol = tick.symbol,
            indexTrend = indexSt.st2.trend,
            regime = currentRegime,
            indexPrice = indexPrice,
            strikePrice = extractStrikePrice(tick.symbol),
            isMarketCompressed = isMarketCompressed(indexSt),
            timestamp = tick.timestamp
        )

        val iZone = zoneEngine.identifyZone(indexPrice, indexSt, indexCandleBuilder.candles.value, true, vix)
        val oZone = zoneEngine.identifyZone(ltp, optionSt, candles, false, vix)
        val matchScore = zoneMatchEngine.calculateMatch(iZone, oZone).toInt()

        val weights = learningEngine.getWeights()
        val metrics = StrikeMetrics(state.candleBuilder.intervalMinutes.toString(), ltp, state.lastOi, state.oiChange, state.volume, state.lastIv, state.lastBid, state.lastAsk, candles, optionSt)

        val intel = optionIntelligenceEngine.analyzeChain(indexPrice, indexSt.st2.trend, indexStrength, listOf(metrics), vix, currentRegime, currentStructure, weights).firstOrNull()

        val expProb = (intel?.expansionProbability ?: 0.0).safe()
        state.premiumExpansion = if (abs(indexStrength.velocity) > 0.1) expProb.coerceAtMost(1000.0) else expProb

        IntelligenceReport(intel, decision, matchScore, iZone, oZone)
    }

    private fun evaluateOptionSignals(
        state: OptionState,
        tick: TickData,
        indicators: Triple<MultiSuperTrendResult, BandInfo, BandInfo>,
        indexSt: MultiSuperTrendResult,
        intel: IntelligenceReport
    ) {
        val (optionSt, optionBand, indexBand) = indicators
        val (optionIntel, brainDecision, zoneMatch, iZone, oZone) = intel

        val ts = tick.timestamp
        val optionCandles = state.candleBuilder.candles.value
        val currentCandleTime = optionCandles.lastOrNull()?.timestamp ?: 0L
        val isCandleJustClosed = currentCandleTime > state.lastClosedTimestamp && optionCandles.lastOrNull()?.isComplete == true
        if (isCandleJustClosed) state.lastClosedTimestamp = currentCandleTime

        val currentState = state.stateEngine.updateState(tick, indexSt, optionSt, indexBand, optionBand, state.strength, currentRegime, isCandleJustClosed)

        checkActivePositionManagement(tick, optionSt)

        if (currentState == TrendState.TREND_FINISHED || currentState == TrendState.TREND_EXHAUSTION) {
            checkExitConditions(tick, indexSt, optionSt)
        }

        val liq = liquidityEngine.analyze(state.lastBid, state.lastAsk, tick.ltp)
        val fake = fakeReversalEngine.analyze(optionCandles, optionSt, state.strength, currentStructure)
        val correlation = correlationEngine.calculate(indexSt, optionSt, tick.symbol)

        val brainAction = brainDecision.action
        val isCorrectType = when (brainAction) {
            MasterAction.BUY -> tick.symbol.contains("CE")
            MasterAction.SELL -> tick.symbol.contains("PE")
            MasterAction.SELL_CALL -> tick.symbol.contains("CE")
            MasterAction.SELL_PUT -> tick.symbol.contains("PE")
            else -> false
        }

        val isMismatched = (brainAction == MasterAction.BUY && tick.symbol.contains("PE")) ||
                          (brainAction == MasterAction.SELL && tick.symbol.contains("CE")) ||
                          (brainAction == MasterAction.SELL_CALL && tick.symbol.contains("PE")) ||
                          (brainAction == MasterAction.SELL_PUT && tick.symbol.contains("CE"))

        val canTrade = !isMismatched && (correlation.matched || isCorrectType) && liq.isTradeable && !fake.isFake
        val decision = masterDecisionEngine.process(currentRegime, currentState, currentStructure, indexStrength, optionIntel, brainDecision.masterProbability, canTrade, strategyConfig.riskLevel)

        val finalAction = when {
            isCorrectType && isCandleJustClosed && liq.isTradeable -> brainAction
            isMismatched -> MasterAction.WAIT
            else -> decision.action
        }
        val enhancedReason = brainDecision.internalLogic + " | " + decision.reason
        val enhancedDecision = decision.copy(action = finalAction, reason = enhancedReason, confidence = brainDecision.masterProbability)

        if ((finalAction == MasterAction.BUY || finalAction == MasterAction.SELL || finalAction == MasterAction.SCALP) && !isCandleJustClosed) return

        handleMasterActionExecution(enhancedDecision, ts, optionBand.currentBand, zoneMatch, iZone, oZone, state.premiumExpansion, optionIntel, state.oiChange, state.ivChange)
        updateTrailingStopLoss(tick, optionSt)
    }

    private fun handleMasterActionExecution(
        decision: MasterDecision,
        timestamp: Long,
        band: Int,
        zoneMatch: Int,
        iZone: ZoneStatus,
        oZone: ZoneStatus,
        expansion: Double,
        strikeInfo: OptionIntelligenceScore?,
        oiChange: Long,
        ivChange: Double
    ) {
        val action = decision.action
        if (action == MasterAction.WAIT || action == MasterAction.NO_TRADE) return

        val strike = strikeInfo ?: decision.recommendedStrike ?: return
        val entryPrice = strike.recommendedPrice

        val userSL = if (strategyConfig.stopLossValue > 0) entryPrice - strategyConfig.stopLossValue else strike.stopLoss
        val finalSL = if (userSL > entryPrice) entryPrice * 0.9 else userSL

        if (finalSL <= EPSILON) return

        val requiresPosition = action in setOf(MasterAction.BUY, MasterAction.SELL, MasterAction.RE_ENTRY, MasterAction.SCALP)
        val posResult = if (requiresPosition) {
            riskManagementEngine.calculatePositionSize(entryPrice, finalSL, decision.confidence, defaultLotSize)
        } else {
            PositionSizeResult(0, 0.0, false)
        }

        if (requiresPosition && (posResult.isBlocked || posResult.quantity <= 0)) return

        val techTarget = oZone.allTargets.getOrNull(0) ?: oZone.nextBandValue
        val userTarget = if (strategyConfig.targetValue > 0) entryPrice + strategyConfig.targetValue else 0.0
        val finalT1 = if (userTarget > entryPrice + EPSILON) userTarget else (if (techTarget <= entryPrice + EPSILON) entryPrice * 1.05 else techTarget)

        val mathT2 = calculateExpectedPremiumTarget(strike, iZone)

        val signal = InstitutionalSignal(
            type = getSignalType(action, strike.symbol),
            action = action,
            confidence = decision.confidence.coerceIn(0, 100),
            reason = if (posResult.isBlocked) posResult.reason else decision.reason,
            optionSymbol = strike.symbol,
            price = entryPrice,
            target = finalT1,
            target2 = if (mathT2 < entryPrice + EPSILON) entryPrice * 1.1 else mathT2,
            finalTarget = oZone.allTargets.lastOrNull() ?: oZone.nextBandValue,
            stopLoss = finalSL,
            quantity = posResult.quantity,
            riskReward = strike.riskReward,
            timestamp = timestamp,
            optionBand = band,
            structure = currentStructure,
            zoneMatchScore = zoneMatch,
            indexZone = iZone,
            optionZone = oZone,
            marketStrength = indexStrength.trendStrength.toInt(),
            premiumExpansion = expansion,
            delta = strike.delta,
            gamma = strike.gamma,
            vega = strike.vega,
            theta = strike.theta,
            ivChange = ivChange,
            oiChange = oiChange
        )

        if (!validateSignal(signal)) return
        if (requiresPosition) {
            riskManagementEngine.updateOnTradeEntry(entryPrice * posResult.quantity)
            optionStates[strike.symbol]?.let {
                it.entryPrice = entryPrice
                it.peakPrice = entryPrice
            }
        }
        emitSignal(signal)
    }

    private fun validateSignal(signal: InstitutionalSignal): Boolean {
        if (signal.price <= EPSILON || signal.stopLoss <= EPSILON || signal.target <= EPSILON) return false
        val requiresQty = signal.action in setOf(MasterAction.BUY, MasterAction.SELL, MasterAction.BUY_CALL, MasterAction.BUY_PUT, MasterAction.RE_ENTRY, MasterAction.SCALP)
        if (requiresQty && signal.quantity <= 0) return false
        return true
    }

    private fun getSignalType(action: MasterAction, symbol: String): String = when(action) {
        MasterAction.EXIT -> TYPE_EXIT
        MasterAction.BOOK_PARTIAL -> TYPE_PARTIAL
        MasterAction.TRAIL -> TYPE_TRAIL
        MasterAction.SCALP -> TYPE_SCALP
        MasterAction.WATCH -> TYPE_WATCH
        MasterAction.PREPARE -> TYPE_PREPARE
        MasterAction.BUY, MasterAction.BUY_CALL -> TYPE_CALL
        MasterAction.SELL, MasterAction.BUY_PUT -> TYPE_PUT
        MasterAction.SELL_CALL -> "SELL_CALL"
        MasterAction.SELL_PUT -> "SELL_PUT"
        MasterAction.RE_ENTRY -> if (symbol.contains("CE")) TYPE_CALL else TYPE_PUT
        MasterAction.SELL_STRANGLE -> "SELL_STRANGLE"
        MasterAction.WAIT, MasterAction.HOLD, MasterAction.NO_TRADE -> "WAIT"
    }

    private fun calculateExpectedPremiumTarget(strike: OptionIntelligenceScore, iZone: ZoneStatus): Double {
        val indexMove = iZone.gapPoints
        val delta = strike.delta
        val gammaBoost = if (strike.isExpiryDay) 1.5 else 1.1
        val expectedMove = (indexMove * delta) * gammaBoost
        val finalTarget = strike.recommendedPrice + expectedMove
        return if (finalTarget < strike.recommendedPrice) strike.recommendedPrice else finalTarget
    }

    private fun checkActivePositionManagement(tick: TickData, optionSt: MultiSuperTrendResult) {
        val symbol = tick.symbol
        val state = optionStates[symbol] ?: return
        val targets = listOf(calculateDynamicTarget(optionSt, 2), calculateDynamicTarget(optionSt, 4), calculateDynamicTarget(optionSt, 6))
        val partialExit = riskManagementEngine.calculatePartialExit(symbol, tick.ltp, state.previousLtp, 100, targets)

        if (partialExit != null) {
            emitSignal(InstitutionalSignal(
                type = TYPE_PARTIAL, action = MasterAction.BOOK_PARTIAL, confidence = 100, reason = partialExit.reason,
                optionSymbol = symbol, price = tick.ltp, target = 0.0, stopLoss = 0.0, quantity = partialExit.quantityToExit,
                timestamp = tick.timestamp, zoneMatchScore = 100, structure = currentStructure
            ))
        }
    }

    private fun updateTrailingStopLoss(tick: TickData, optionSt: MultiSuperTrendResult) {
        val symbol = tick.symbol
        val state = optionStates[symbol] ?: return
        if (state.entryPrice <= 0) return

        // Trail from PEAK price since entry
        val currentSL = state.peakPrice * 0.95

        val bandsList = getBandsList(optionSt)
        var newSL = currentSL

        bandsList.forEach { bandPrice ->
            if (optionSt.st2.trend == 1) {
                if (bandPrice > newSL && bandPrice < tick.ltp - EPSILON) newSL = bandPrice
            } else {
                if (bandPrice < newSL && bandPrice > tick.ltp + EPSILON) newSL = bandPrice
            }
        }

        if (abs(newSL - currentSL) > (tick.ltp * 0.001)) {
             emitSignal(InstitutionalSignal(TYPE_TRAIL, MasterAction.TRAIL, 100, "Band Shift", symbol, tick.ltp, 0.0, 0.0, 0.0, newSL, timestamp = tick.timestamp, structure = currentStructure, zoneMatchScore = 100))
        }
    }

    private fun getBandsList(st: MultiSuperTrendResult) = listOf(
        st.st2.value, st.st3.value, st.st4.value, st.st5.value, st.st6.value, st.st7.value, st.st8.value
    )

    private fun calculateDynamicTarget(st: MultiSuperTrendResult, currentBand: Int): Double {
        val multiplier = if (currentStructure == MarketStructure.EXPANSION) 1.05 else 1.0
        val bands = getBandsList(st)
        val targetIndex = (currentBand - 1).coerceIn(0, 6)
        return if (targetIndex < 6) bands[targetIndex + 1] * multiplier else bands[6] * 1.02 * multiplier
    }

    private fun checkExitConditions(tick: TickData, indexSt: MultiSuperTrendResult, optionSt: MultiSuperTrendResult) {
        val symbol = tick.symbol
        if (currentStructure == MarketStructure.STRUCTURE_BREAK) {
            emitExitSignal(symbol, "Market Structure Break", tick.ltp, tick.timestamp)
            return
        }

        val isCall = symbol.contains("CE")
        val isPut = symbol.contains("PE")
        val indexTrend = indexSt.st2.trend
        val optionTrend = optionSt.st2.trend

        val correlation = correlationEngine.calculate(indexSt, optionSt, symbol)

        val isBroken = when {
            isCall -> indexTrend == -1 || optionTrend == -1 || !correlation.matched
            isPut -> indexTrend == 1 || optionTrend == -1 || !correlation.matched
            else -> indexTrend != optionTrend
        }

        if (isBroken) {
             emitExitSignal(symbol, "Market Mismatch", tick.ltp, tick.timestamp)
             return
        }

        if (optionStates[symbol]?.strength?.isExhausted == true) {
            emitExitSignal(symbol, "Strength Exhaustion", tick.ltp, tick.timestamp)
        }
    }

    private fun emitExitSignal(symbol: String, reason: String, price: Double, timestamp: Long) {
        emitSignal(InstitutionalSignal(TYPE_EXIT, MasterAction.EXIT, 100, reason, symbol, price, 0.0, 0.0, 0.0, 0.0, timestamp = timestamp, structure = currentStructure, zoneMatchScore = 100))
    }

    private fun emitSignal(signal: InstitutionalSignal) {
        val key = "${signal.optionSymbol}_${signal.type}"
        val lastTime = lastSignalTimestamps[key] ?: 0L

        // Use signal timestamp for dedup to avoid duplicate spam within window
        if (signal.timestamp - lastTime < SIGNAL_SPAM_WINDOW_MS) return

        val current = _signals.value
        val isDuplicate = current.any {
            it.optionSymbol == signal.optionSymbol && it.type == signal.type && it.timestamp == signal.timestamp
        }

        if (!isDuplicate) {
            lastSignalTimestamps[key] = signal.timestamp
            val updated = current + signal
            _signals.value = if (updated.size > MAX_SIGNAL_HISTORY) updated.takeLast(MAX_SIGNAL_HISTORY) else updated
        }
    }

    private fun cleanupOldOptions(now: Long) {
        val iterator = optionStates.iterator()
        while (iterator.hasNext()) {
            val entry = iterator.next()
            if (now - entry.value.lastUpdateTime > 3600000) {
                iterator.remove()
                Log.d(TAG, "Cleaned up stale option state: ${entry.key}")
            }
        }
        lastCleanupTime = now
    }

    fun getIndexStrength() = indexStrength
    fun getOptionStrength(symbol: String) = optionStates[symbol]?.strength ?: StrengthMetrics()
    fun getTrendLifecycle() = trendStateEngine.context
    fun getMarketRegime() = currentRegime
    fun getMarketStructure() = currentStructure
    fun getTrendState() = trendStateEngine.context.state
    fun getOptionMetrics(symbol: String): OptionState? = optionStates[symbol]
    fun getLearningStats() = learningEngine.getStats()
    fun getLearningWeights() = learningEngine.getWeights()
    fun getRiskState() = riskManagementEngine.getState()

    fun getIntelligence(symbol: String): OptionIntelligence? {
        val state = optionStates[symbol] ?: return null
        val candles = state.candleBuilder.candles.value
        val optionSt = state.stEngine.calculate(candles) ?: return null
        val indexSt = indexStEngine.calculate(indexCandleBuilder.candles.value) ?: return null
        return OptionIntelligence(
            fake = fakeReversalEngine.analyze(candles, optionSt, state.strength, currentStructure),
            liquidity = liquidityEngine.analyze(state.lastBid, state.lastAsk, state.lastLtp),
            correlation = correlationEngine.calculate(indexSt, optionSt, symbol)
        )
    }

    data class OptionIntelligence(val fake: FakeReversalResult, val liquidity: LiquidityResult, val correlation: CorrelationResult)
    private data class IntelligenceReport(val intelligence: OptionIntelligenceScore?, val centralDecision: CentralDecision, val zoneMatchScore: Int, val indexZone: ZoneStatus, val optionZone: ZoneStatus)

    fun getIndexMultiTrend() = _indexMultiTrend.value
    fun getIndexCandles() = indexCandleBuilder.candles.value
    fun getIndexAgents(currentPrice: Double, vix: Double = 15.0) = indexAgents.map { it.process(candles = indexCandleBuilder.candles.value, currentPrice = currentPrice, timestamp = indexCandleBuilder.candles.value.lastOrNull()?.timestamp ?: 0L, vix = vix) }
    fun getOptionAgents(symbol: String, vix: Double = 15.0): List<AgentReport> {
        val state = optionStates[symbol] ?: return emptyList()
        return state.agents.map { it.process(candles = state.candleBuilder.candles.value, currentPrice = state.lastLtp, timestamp = state.lastUpdateTime, vix = vix) }
    }
    fun getOptionMultiTrend(symbol: String) = optionStates[symbol]?.let { s ->
        s.candleBuilder.candles.value.let { if (it.isNotEmpty()) s.stEngine.calculate(it) else null }
    }

    fun onTradeCompleted(entry: TradeJournalEntry) {
        learningEngine.recordTrade(entry)
        riskManagementEngine.updateOnTradeExit(entry.profit, entry.entryPrice * entry.quantity)
        trendMemoryEngine.update(entry.profit > 0, 0)
    }

    fun emergencyStop() = riskManagementEngine.emergencyStop()

    fun dispose() {
        processingScope.cancel()
    }

    fun reset() {
        indexStEngine.reset()
        optionStates.values.forEach { it.stEngine.reset() }
        trendStateEngine.reset()
        masterDecisionEngine.reset()
        riskManagementEngine.resetDaily()
    }
}
